### ISSUE TITLE
run openchange-ocsmanager.

### ISSUE THREAD

**Issue by MisterM74** [openchange/openchange#246]
hello

I have this when I run openchange-ocsmanager.

Traceback (most recent call last):
  File "/usr/bin/paster", line 4, in <module>
    command.run()
  File "/usr/lib/python2.7/dist-packages/paste/script/command.py", line 104, in run
    invoke(command, command_name, options, args[1:])
  File "/usr/lib/python2.7/dist-packages/paste/script/command.py", line 143, in invoke
    exit_code = runner.run(args)
  File "/usr/lib/python2.7/dist-packages/paste/script/command.py", line 238, in run
    result = self.command()
  File "/usr/lib/python2.7/dist-packages/paste/script/serve.py", line 284, in command
    relative_to=base, global_conf=vars)
  File "/usr/lib/python2.7/dist-packages/paste/script/serve.py", line 321, in loadapp
    **kw)
  File "/usr/lib/python2.7/dist-packages/paste/deploy/loadwsgi.py", line 247, in loadapp
    return loadobj(APP, uri, name=name, **kw)
  File "/usr/lib/python2.7/dist-packages/paste/deploy/loadwsgi.py", line 271, in loadobj
    global_conf=global_conf)
  File "/usr/lib/python2.7/dist-packages/paste/deploy/loadwsgi.py", line 296, in loadcontext
    global_conf=global_conf)
  File "/usr/lib/python2.7/dist-packages/paste/deploy/loadwsgi.py", line 320, in _loadconfig
    return loader.get_context(object_type, name, global_conf)
  File "/usr/lib/python2.7/dist-packages/paste/deploy/loadwsgi.py", line 454, in get_context
    section)
  File "/usr/lib/python2.7/dist-packages/paste/deploy/loadwsgi.py", line 476, in _context_from_use
    object_type, name=use, global_conf=global_conf)
  File "/usr/lib/python2.7/dist-packages/paste/deploy/loadwsgi.py", line 406, in get_context
    global_conf=global_conf)
  File "/usr/lib/python2.7/dist-packages/paste/deploy/loadwsgi.py", line 296, in loadcontext
    global_conf=global_conf)
  File "/usr/lib/python2.7/dist-packages/paste/deploy/loadwsgi.py", line 328, in _loadegg
    return loader.get_context(object_type, name, global_conf)
  File "/usr/lib/python2.7/dist-packages/paste/deploy/loadwsgi.py", line 620, in get_context
    object_type, name=name)
  File "/usr/lib/python2.7/dist-packages/paste/deploy/loadwsgi.py", line 646, in find_egg_entry_point
    possible.append((entry.load(), protocol, entry.name))
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 1989, in load
    entry = __import__(self.module_name, globals(),globals(), ['__name__'])
  File "/usr/lib/python2.7/dist-packages/ocsmanager/config/middleware.py", line 14, in <module>
    from ocsmanager.config.environment import load_environment
  File "/usr/lib/python2.7/dist-packages/ocsmanager/config/environment.py", line 34, in <module>
    import openchange.mapistore as mapistore
ImportError: No module named mapistore
Removing PID file /var/run/ocsmanager/ocsmanager.pid

Any idea?

Yours

Michel

**Comment by jkerihuel** [comment]
python mapistore bindings were not compiled or are not in pythonpath

**Comment by MisterM74** [comment]
hello
For operation there in need?

Because I use the packages compiled by SOGo

Also, I recompile my DNS server with the addition of the "'--with-dlz-dlopen = yes", but when I restart it, adding course "include" / var / lib / samba / private / named.conf.update ", it shows me an error:
  /var/lib/samba/private/named.conf.update:2: unknown option 'update-policy'

A you have an idea

Debian Wheezy server.
Openchange version / deb extension - 2.2.5

Yours
Mz

**Comment by jkerihuel** [comment]
I don't understand your question sorry. Furthermore I would prefer you to open 1 ticket per question rather than reuse the same conversation over and over.

Br,
Julien.

**Comment by MisterM74** [comment]
Ticket?
Or?

**Comment by jkerihuel** [comment]
Issue # on github: https://github.com/openchange/openchange/issues/new
