### ISSUE TITLE
can't start ocsmanager

### ISSUE THREAD

**Issue by alejandro-anv** [openchange/openchange#411]
Centos 7. Openchange compiled from sources. When I try to start ocsmanager, I receive this error:
# paster serve /etc/ocsmanager/ocsmanager.ini --pid-file /var/run/ocsmanager.pid

Traceback (most recent call last):
  File "/usr/bin/paster", line 9, in <module>
    load_entry_point('PasteScript==1.7.5', 'console_scripts', 'paster')()
  File "/usr/lib/python2.7/site-packages/paste/script/command.py", line 104, in run
    invoke(command, command_name, options, args[1:])
  File "/usr/lib/python2.7/site-packages/paste/script/command.py", line 143, in invoke
    exit_code = runner.run(args)
  File "/usr/lib/python2.7/site-packages/paste/script/command.py", line 238, in run
    result = self.command()
  File "/usr/lib/python2.7/site-packages/paste/script/serve.py", line 284, in command
    relative_to=base, global_conf=vars)
  File "/usr/lib/python2.7/site-packages/paste/script/serve.py", line 321, in loadapp
    *_kw)
  File "/usr/lib/python2.7/site-packages/paste/deploy/loadwsgi.py", line 247, in loadapp
    return loadobj(APP, uri, name=name, *_kw)
  File "/usr/lib/python2.7/site-packages/paste/deploy/loadwsgi.py", line 272, in loadobj
    return context.create()
  File "/usr/lib/python2.7/site-packages/paste/deploy/loadwsgi.py", line 710, in create
    return self.object_type.invoke(self)
  File "/usr/lib/python2.7/site-packages/paste/deploy/loadwsgi.py", line 146, in invoke
    return fix_call(context.object, context.global_conf, *_context.local_conf)
  File "/usr/lib/python2.7/site-packages/paste/deploy/util.py", line 56, in fix_call
    val = callable(_args, **kw)
  File "/usr/local/samba/lib/python2.7/site-packages/ocsmanager/config/middleware.py", line 43, in make_app
    config = load_environment(global_conf, app_conf)
  File "/usr/local/samba/lib/python2.7/site-packages/ocsmanager/config/environment.py", line 157, in load_environment
    mstore = mapistore.MAPIStore(config['ocsmanager']['main']['mapistore_root'])
SystemError: error in mapistore_init
Removing PID file /var/run/ocsmanager.pid

**Comment by falsagoff** [comment]
Me too. Here is what I get when I run:
sudo PYTHONPATH=$PYTHONPATH paster serve /etc/ocsmanager/ocsmanager.ini --pid-file /var/run/ocsmanager.pid --log-file /var/log/ocsmanager.log
mapiproxy/libmapistore/mapistore_backend.c:277(mapistore_backend_init): No mapistore backends available (using backend path '(null)').
mapiproxy/libmapistore/mapistore_interface.c:88(mapistore_init): mapistore_backend_init: Storage backend initialization failed

The /var/log/ocsmanager.log shows:
...
  File "/usr/lib/python2.7/site-packages/paste/deploy/loadwsgi.py", line 146, in invoke
    return fix_call(context.object, context.global_conf, *_context.local_conf)
  File "/usr/lib/python2.7/site-packages/paste/deploy/util.py", line 56, in fix_call
    val = callable(_args, **kw)
  File "/usr/local/samba/lib/python2.7/site-packages/ocsmanager/config/middleware.py", line 43, in make_app
    config = load_environment(global_conf, app_conf)
  File "/usr/local/samba/lib/python2.7/site-packages/ocsmanager/config/environment.py", line 182, in load_environment
    mstore = mapistore.MAPIStore(config['ocsmanager']['main']['mapistore_root'])
SystemError: error in mapistore_init
Removing PID file /var/run/ocsmanager.pid

Actually I think I will post a new issue
